services:
  - type: web
    name: slot-monitor-bot
    runtime: docker
    plan: free
    healthCheckPath: /ping
    envVars:
      - key: PORT
        value: "10000"
      - key: JAVA_OPTS
        value: "-XX:MaxRAMPercentage=70 -XX:+ExitOnOutOfMemoryError"
      - key: CHECK_INTERVAL
        value: "30000"
      - key: DAYS_BACK
        value: "7"
      - key: DAYS_FORWARD
        value: "30"
      - key: ORGANIZATION_ID
        value: "b4b36a53-d253-4840-9000-49061d74bf50"
      - key: TASK_ID
        value: "1361446"
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
      - key: TOKEN_ID
        sync: false
      - key: JSESSIONID
        sync: false
